name: Build and Test
on: [pull_request, push]
jobs:
  build-and-test:
    runs-on: ["self-hosted", "Linux"]
    strategy:
      matrix:
        DISTRO: [run] #["tomcat", "wildfly", "run"]
        EE: ["false"] # ["false", "true"]
    steps:
      - name: Install docker-compose
        run:  |-
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - uses: actions/checkout@v2
      - name: Execute pipeline
        run: ./pipeline.sh
        env:
          DISTRO: ${{ matrix.DISTRO }}
          EE: ${{ matrix.EE }}
